### ISSUE TITLE
Use routing_client for GET/PUT options in the example

### ISSUE THREAD

**Issue by chandraprakash** [dirvine/routing#193]
Use routing_client for GET/PUT options in the example.

**Comment by maqi** [comment]
need a decision that whether the RoutingClient::new() does not need to take the ID of the bootstrap node (only Endpoint required) or stays what it is now.
Not to take the ID means a swapping ID process needs to be undertake, which involves some work in maidsafe_client.
Stays what it is now means a bootstrap file need to be created/updated/accessed in routing example.

**Comment by dirvine** [comment]
Ideally it should not and crust will automatically connect to a node (any node). It does mean that client also does need to do the same as node does in swapping ID's though I am afraid. I cannot see an easy way around that. The point is that it should be very rare for routing node or client to have to pass a bootstrap endpoint ever (except in very first connect and then crust will pick up and maintain bootstrap lists) . It will be crusts job to keep the bootstrap info/beacon etc. all up to date. 

So we will need an initial bootstrap cache file to be installed with clients and vaults (with prob out fixed endpoints). for the tests we can pass this via a `client::with_endpoint()` instead of `client::new()`to emulate this. It's a PITA but crust will remove this requirement very soon.

**Comment by maqi** [comment]
https://github.com/dirvine/routing/pull/200

**Comment by chandraprakash** [comment]
run() method of routing client should be internal and not public. Previous routing_client code was doing it internally. Run receives messages from crust to routing, upper layer should not have any access/control to this. This also applies for routing node. 

As the code is merged, I will raise a separate issue for this.
